# 서버 포트 설정
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# database 연동 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: c##studyproject
    password: 1234
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

# mybatis
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update